Refactor the UI and service layer, add retrieval for home screen
Iconica-Development/flutter_availability pull request #9
Opened 2024-07-05 13:21 UTC by FlutterJoey

2024-07-05 13:41 UTC, PureTryOut requested changes

2024-07-05 13:41 UTC, PureTryOut commented on packages/flutter_availability/lib/src/routes.dart
> +  DateTime date,
Unnecessary trailing comma

2024-07-05 13:41 UTC, PureTryOut commented on packages/flutter_availability/lib/src/ui/screens/availability_overview.dart
> +      Navigator.of(context).pop();
Shouldn't this be handled outside of this widget like the other navigation callbacks?

2024-07-05 13:41 UTC, PureTryOut commented on packages/flutter_availability/lib/src/ui/screens/template_availability_day_overview.dart
> +                                  labelText: "Begin tijd",
Use localizations

2024-07-05 13:41 UTC, PureTryOut commented on packages/flutter_availability/lib/src/ui/screens/template_availability_day_overview.dart
> +                const Text("Clear availability for today"),
Use localizations

2024-07-05 13:41 UTC, PureTryOut commented on packages/flutter_availability/lib/src/ui/screens/template_availability_day_overview.dart
> +                      height: 16,
Unnecessary trailing comma

2024-07-05 13:41 UTC, PureTryOut commented on packages/flutter_availability/lib/src/ui/screens/template_availability_day_overview.dart
> +                    const Text("Add pause (optional)"),
Use localizations

2024-07-05 13:41 UTC, PureTryOut commented on packages/flutter_availability/lib/src/ui/screens/template_availability_day_overview.dart
> +                            onTap: () async {
Extract the function out of the widget tree

2024-07-05 13:41 UTC, PureTryOut commented on packages/flutter_availability/lib/src/ui/screens/template_availability_day_overview.dart
> +                                    " minutes  |  ",
Use localizatinos

2024-07-05 13:41 UTC, PureTryOut commented on packages/flutter_availability/lib/src/ui/screens/template_availability_day_overview.dart
> +                                color: Colors.lightBlue,
Unnecessary trailing coma

2024-07-05 13:41 UTC, PureTryOut commented on packages/flutter_availability/lib/src/ui/screens/template_availability_day_overview.dart
> +                                    "$start - "
This text would be clearer on one line, don't split it up

2024-07-05 13:41 UTC, PureTryOut commented on packages/flutter_availability/lib/src/ui/screens/template_availability_day_overview.dart
> +                                        _availability.breaks.remove(breakModel);
Extract this function outside of the widget tree

2024-07-05 13:41 UTC, PureTryOut commented on packages/flutter_availability/lib/src/ui/screens/template_availability_day_overview.dart
> +                      child: const Text("Add"),
Use localizations

2024-07-05 13:41 UTC, PureTryOut commented on packages/flutter_availability/lib/src/ui/screens/template_availability_day_overview.dart
> +              child: const Text(""),
An empty button?

2024-07-05 13:41 UTC, PureTryOut commented on packages/flutter_availability/lib/src/ui/widgets/default_base_screen.dart
> +        child: child,
Unnecessary trailing comma

2024-07-05 13:41 UTC, PureTryOut commented on packages/flutter_availability/lib/src/service/availability_service.dart
> +  /// Returns a stream where data from
where data from... what?

2024-07-05 13:41 UTC, PureTryOut commented on packages/flutter_availability/lib/src/service/local_data_interface.dart
> +          id: _generateId(),
Unnecessary trailing comma

2024-07-05 14:02 UTC, freekvandeven approved these changes

2024-07-05 14:16 UTC, FlutterJoey commented on packages/flutter_availability/lib/src/routes.dart
> +  DateTime date,
I like to see properties of a function to be listed below, because it separates them from the rest for legibility.

2024-07-08 06:51 UTC, PureTryOut approved these changes

2024-07-08 06:51 UTC, merged